export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const SET_COUNTER = 'SET_COUNTER';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const CHANGE_QUEUE = 'CHANGE_QUEUE';
export const SET_CURRENT_SONG_ID = 'SET_CURRENT_SONG_ID';
export const CHANGE_REPEAT = 'CHANGE_REPEAT';
export const STOP = 'STOP';
