export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const SET_COUNTER = 'SET_COUNTER';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const CHANGE_QUEUE = 'CHANGE_QUEUE';
export const GET_CURRENT_SONG = 'GET_CURRENT_SONG';
export const CHANGE_REPEAT = 'CHANGE_REPEAT';
